[package]
name = "bevy_sandbox_ragdoll"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.16"
bevy_rapier2d = "0.31"
rand = "0.9"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
